name: ikarusapp
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_riverpod:
  shared_preferences:
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  ionicons: ^0.2.2
  google_maps_flutter: ^2.13.1
  google_places_flutter: ^2.1.1
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  printing: ^5.14.2
  pdf: ^3.11.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  carousel_slider: ^5.1.1
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/splash/
    - assets/icons/
    - assets/icons/station/
    - assets/icons/connectortypes/
    - assets/map/map_style.json
    - assets/navbar/
    - assets/card/
    - assets/socialmedia/


  fonts:
    - family: splash
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
